Feature/donghoon/init llm worker
ainize-team/LLM-Worker pull request #1
Opened 2022-07-26 09:41 UTC by 589hero

LLM서빙을 위한 Celery Worker 초기화 작업입니다.

2022-07-26 09:46 UTC, byeongal requested changes

2022-07-26 09:46 UTC, byeongal commented on requirements.txt
> +python-dotenv==0.20.0
prod 에는 dotenv 가 있으면 안됩니다 지워주세요.

2022-07-26 09:46 UTC, byeongal commented on setup.cfg
>      worker
필요 없을 것 같습니다.

2022-07-26 09:46 UTC, byeongal commented on worker/configs/config.py
> +    model_path: str = ""
model_path 없으면 에러 뜨도록 수정 해주세요.

2022-07-26 09:46 UTC, byeongal commented on worker/ml_model.py
> +        else:
gpu가 없는 경우 ( CPU 서빙 ) 지원 하도록 업데이트 부탁 드려요

`self.model = AutoModelForCausalLM.from_pretrained(model_path)`

2022-07-26 09:46 UTC, byeongal commented on worker/tasks.py
> +        "inputs": llm.tokenizer.encode(data["prompt"], return_tensors="pt").cuda(),
cpu 환경 지원 하도록 기능 추가

2022-07-26 09:46 UTC, byeongal commented on README.md
> +1. install dev package.
README.md 에 사용법 추가 부탁 드려요

2022-07-26 10:58 UTC, godhw commented on worker/ml_model.py
> +    def load_model(self, model_path: str, use_fast: bool = True):
use_fast = True는 입력되지 않았을 때 default로 설정되는 건가요?

2022-07-26 11:01 UTC, 589hero commented on requirements.txt
> +python-dotenv==0.20.0
반영했습니다!

2022-07-26 11:01 UTC, 589hero commented on setup.cfg
>      worker
반영했습니다!

2022-07-26 11:01 UTC, 589hero commented on worker/configs/config.py
> +    model_path: str = ""
반영했습니다!

2022-07-26 11:01 UTC, 589hero commented on worker/ml_model.py
> +        else:
반영했습니다!

2022-07-26 11:01 UTC, 589hero commented on worker/tasks.py
> +        "inputs": llm.tokenizer.encode(data["prompt"], return_tensors="pt").cuda(),
반영했습니다!

2022-07-26 11:01 UTC, 589hero commented on README.md
> +1. install dev package.
반영했습니다!

2022-07-26 11:03 UTC, 589hero commented on worker/ml_model.py
> +    def load_model(self, model_path: str, use_fast: bool = True):
네네 맞습니다.

2022-07-26 11:51 UTC, jikerbug submitted a review, later dismissed
LGTM

2022-07-26 13:01 UTC, byeongal requested changes

2022-07-26 13:01 UTC, byeongal commented on README.md
> +1. install dev package.
rabbitmq 나 redis 가 필요한 상황이면 해당 사항도 업데이트 부탁 드려요

2022-07-26 13:01 UTC, byeongal commented on requirements-dev.txt
> +transformers==4.20.1
torch 가 없습니다.

2022-07-26 13:01 UTC, byeongal commented on worker/tasks.py
> +def generate(self, data: Dict) -> Union[str, Dict]:
Union[List[str], Dict] 로 수정 부탁 드립니다.
더 좋은건 pydantic 써서 구조화 하는게 더 좋을 것 같습니다.

2022-07-26 13:10 UTC, 589hero commented on requirements-dev.txt
> +transformers==4.20.1
transformers가 설치되면서 torch==1.12.0도 같이 설치가 되는데, 따로 작성을 해줘야될까요?

2022-07-27 01:51 UTC, godhw commented on requirements-dev.txt
> +transformers==4.20.1
혹시 dotenv는 안쓰는 건가요?

2022-07-27 02:10 UTC, 589hero commented on worker/tasks.py
> +def generate(self, data: Dict) -> Union[str, Dict]:
pydantic 모델을 이용해보았는데 json serialization 에러가 발생합니다. 에러를 해결하기 위해서는 
```
return PydanticModel().json()
```
이런 형태로 작성해야하는데, Pydantic을 쓰는게 나을까요?

2022-07-27 02:10 UTC, 589hero commented on requirements-dev.txt
> +transformers==4.20.1
테스트시에 필요하면 직접 추가해서 사용해야 합니다.

2022-07-27 02:46 UTC, jujeongho0 commented
LGTM

2022-07-27 02:46 UTC, jujeongho0 approved these changes, later dismissed
LGTM

2022-07-27 02:48 UTC, godhw approved these changes, later dismissed

2022-07-27 03:24 UTC, godhw commented on README.md
> +1. install dev package.
How to test Celery worker?

1. Run celery worker
2. execute python idle by `python` in shell
3. import task's generate function. ex) `from tasks import generate` in worker dir
4. import `AsyncResult` by `from celery.result import AsyncResult`
5. Use `generate` function. If it works correctly, return `task_id` in AsyncResult form.
 - Check input of function! ex) `task = generate.delay(input)`
 - `.delay` used for async request.
 - If `task` is `string` type, use `result = AsyncResult(task)`
 6. Use `.ready()` to check if the result has been generated. If it returns `True`, use `.get()` to get the result.
 - ex) `task.ready()`, if `True`, `task.get()`

2022-07-27 03:32 UTC, 589hero commented on README.md
> +1. install dev package.
반영했습니다!

2022-07-27 03:32 UTC, 589hero commented on requirements-dev.txt
> +transformers==4.20.1
반영했습니다!

2022-07-27 03:32 UTC, 589hero commented on worker/tasks.py
> +def generate(self, data: Dict) -> Union[str, Dict]:
반영했습니다!

2022-07-27 03:32 UTC, 589hero commented on README.md
> +1. install dev package.
반영했습니다!

2022-07-27 03:44 UTC, godhw requested changes

2022-07-27 03:44 UTC, godhw commented on README.md
> +from celery_tasks.tasks import generate
디렉터리 구조 상 `from tasks import generate`로 하는 것이 맞는 것 같습니다.

2022-07-27 03:44 UTC, godhw commented on worker/tasks.py
> +from worker import app
`.worker`로 안해도 될까요?

2022-07-27 05:34 UTC, 589hero commented on worker/tasks.py
> +from worker import app
worker 디렉토리 이동 한 후에 worker를 실행하므로 ```.```을 안 붙여도 됩니다!

2022-07-27 05:36 UTC, 589hero commented on README.md
> +from celery_tasks.tasks import generate
반영했습니다!

2022-07-27 05:41 UTC, godhw approved these changes
LGTM

2022-07-27 05:47 UTC, byeongal approved these changes
LGTM!

2022-07-27 06:25 UTC, jujeongho0 approved these changes
LGTM

2022-07-27 06:35 UTC, merged